name        : libxkbfile
version     : 1.0.9
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.0.9.tar.gz : 95df50570f38e720fb79976f603761ae6eff761613eb56f258c3cb6bab4fd5e3
license     :
    - MIT
summary     : X11 keyboard file manipulation library
component   : xorg.library
builddeps   :
    - pkgconfig(kbproto)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
description : |
    libxkbfile provides an interface to read and manipulate description files for XKB, the X11 keyboard configuration extension
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
