name       : libxkbfile
version    : 1.1.1
release    : 15
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.1.tar.gz : 87faee6d4873c5631e8bb53e85134084b862185da682de8617f08ca18d82e216
license    : MIT
component  : xorg.library
summary    : X11 keyboard file manipulation library
description: |
    libxkbfile provides an interface to read and manipulate description files for XKB, the X11 keyboard configuration extension
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig(xproto)
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
